//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC.Desktop.Main.Resources.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AC.Desktop.Main.Resources.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent:.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A To B Connection Type.
        /// </summary>
        public static string AToBConnectionType {
            get {
                return ResourceManager.GetString("AToBConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribuet Name.
        /// </summary>
        public static string AttribuetName {
            get {
                return ResourceManager.GetString("AttribuetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B To A Connection Type.
        /// </summary>
        public static string BToAConnectionType {
            get {
                return ResourceManager.GetString("BToAConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Name.
        /// </summary>
        public static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Rule.
        /// </summary>
        public static string ConnectionRule {
            get {
                return ResourceManager.GetString("ConnectionRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections From This Node.
        /// </summary>
        public static string ConnectionsFrom {
            get {
                return ResourceManager.GetString("ConnectionsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections To This Node.
        /// </summary>
        public static string ConnectionsTo {
            get {
                return ResourceManager.GetString("ConnectionsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Type Attribuets.
        /// </summary>
        public static string ConnectionTypeAttribuets {
            get {
                return ResourceManager.GetString("ConnectionTypeAttribuets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Type Name.
        /// </summary>
        public static string ConnectionTypeName {
            get {
                return ResourceManager.GetString("ConnectionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Types.
        /// </summary>
        public static string ConnectionTypes {
            get {
                return ResourceManager.GetString("ConnectionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entery Node:.
        /// </summary>
        public static string EnteryNode {
            get {
                return ResourceManager.GetString("EnteryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Name:.
        /// </summary>
        public static string GraphName {
            get {
                return ResourceManager.GetString("GraphName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        public static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Abstract.
        /// </summary>
        public static string IsAbstract {
            get {
                return ResourceManager.GetString("IsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node A.
        /// </summary>
        public static string NodeA {
            get {
                return ResourceManager.GetString("NodeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Attributes.
        /// </summary>
        public static string NodeAttributes {
            get {
                return ResourceManager.GetString("NodeAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node B.
        /// </summary>
        public static string NodeB {
            get {
                return ResourceManager.GetString("NodeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name.
        /// </summary>
        public static string NodeName {
            get {
                return ResourceManager.GetString("NodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        public static string Nodes {
            get {
                return ResourceManager.GetString("Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrites.
        /// </summary>
        public static string Overwrites {
            get {
                return ResourceManager.GetString("Overwrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Session.
        /// </summary>
        public static string StartSession {
            get {
                return ResourceManager.GetString("StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight A To B.
        /// </summary>
        public static string WeightA2B {
            get {
                return ResourceManager.GetString("WeightA2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight B To A.
        /// </summary>
        public static string WeightB2A {
            get {
                return ResourceManager.GetString("WeightB2A", resourceCulture);
            }
        }
    }
}
